# Credits: https://www.linkedin.com/pulse/deploy-aws-lambda-function-using-s3-bucket-github-martinez-cartagena/
#          https://repost.aws/knowledge-center/lambda-python-package-compatible
name: 'Build and upload to S3 Bucket'

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
    - 'src/**'

jobs:

  Build_and_Upload:
    permissions:
      actions: write
      contents: write
    
    runs-on: ubuntu-latest
    environment: pdn

    steps:
      - uses: actions/checkout@v3

      - name: 'Install Python Libraries'
        id: 'install_libraries'
        run: |
          pip install -t src \
              --implementation cp \
              --only-binary=:all: --upgrade \
              -r requirements.txt

      
      - name: 'Create Zip File'
        id: 'create_package'
        run: |
          zip -r gh_archive_data_loader.zip src/*


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: 'Upload to S3 Bucket'
        run: aws s3 cp gh_archive_data_loader.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/${{ secrets.AWS_S3_BUCKET_KEY }}

      - name: 'Update Lambda Function Code'
        run: |
          aws lambda update-function-code \
           --function-name gh-archive-data-loader \
           --s3-bucket ${{ secrets.AWS_S3_BUCKET_NAME }} \
           --s3-key ${{ secrets.AWS_S3_BUCKET_KEY }}
